forge "http://forge.puppetlabs.com"

mod 'puppetlabs/firewall'
mod 'stahnma/epel'
mod 'puppetlabs/java'
mod 'puppetlabs/tomcat'
mod 'example42/solr'
mod 'LafayetteCollegeLibraries/fedora_commons_solr',
    :git => "git@github.com:LafayetteCollegeLibraries/puppet-fedora_commons_solr.git",
    :ref => '01558ae78685c12f5cb3add8615623c1d03f9ac4'
mod "LafayetteCollegeLibraries/fedora_commons",
    :git => "git@github.com:LafayetteCollegeLibraries/puppet-fedora_commons.git",
    :ref => '684663c81a8de925ac6dda13e78ebd5214a20a24'
mod 'jrgriffiniii/fedoragsearch',
    :git => "git@github.com:jrgriffiniii/puppet-fedoragsearch.git",
    :ref => '39192aa19c96495b2b025e5ca2e26ac0e4e10cf1'

