forge "http://forge.puppetlabs.com"

mod 'example42/puppi'
mod 'puppetlabs/firewall'
mod 'stahnma/epel'
mod 'puppetlabs/java'

mod 'LafayetteCollegeLibraries/fedora_commons_solr',
     :git => "https://github.com/LafayetteCollegeLibraries/puppet-fedora_commons_solr.git",
     :ref => 'c5d5e2b9d93ad67853b271f982343def4a6567cb'

mod "LafayetteCollegeLibraries/fedora_commons",
    :git => "https://github.com/LafayetteCollegeLibraries/puppet-fedora_commons.git",
    :ref => 'fcac17124f67b3b7b9314e024647d8b8f311d1b5'

mod 'LafayetteCollegeLibraries/fedoragsearch',
    :git => "https://github.com/LafayetteCollegeLibraries/puppet-fedoragsearch.git",
